### ISSUE TITLE
https://?

### ISSUE THREAD

**Issue by ehfd** [jamesinc/imgur-upload#1]
How do I set up this program to recieve https://i.imgur.com... instead of http??
Thank you.

**Comment by jamesinc** [comment]
@kimdenny the Imgur API responds with an http:// link. If you wanted to rewrite it as an https link, you'd need to modify the source: https://github.com/jamesinc/imgur-upload/blob/master/js/imgurupload.js#L56

See there, the getLinkCode function, you could do a replace on data.link, i.e. `data.link=data.link.replace("http://", "https://");`

**Comment by ehfd** [comment]
Hmm... Doesn't seen to work when I pasted 
data.link=data.link.replace("http://", "https://");
on line 57... I'm sorry to bug you... It's a https only site

**Comment by ehfd** [comment]
OK min.js did it
(closed)
