### ISSUE TITLE
upload without drag and drop

### ISSUE THREAD

**Issue by nathnx** [jamesinc/imgur-upload#2]
How can I use this plugin with 'Advance Editor' plugin (by clicking/selecting some icon in the editor panel to upload or use mobile browser to upload image to Imgur). ?

**Comment by jamesinc** [comment]
@TNattX sorry I didn't respond sooner - currently this plugin doesn't have any nice integration with Advance Editor. My advice would be if you want to use this plugin, disable Advance Editor's built-in functionality.
